# Generated by Django 2.2.6 on 2020-04-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='player_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerSide.Player', verbose_name='player_address'),
        ),
    ]
