# Generated by Django 2.2.6 on 2020-04-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='game', editable=False, max_length=5, unique=True),
        ),
    ]
