# Generated by Django 3.0.6 on 2020-06-03 19:12

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('ServerSide', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='map',
			name='map_address',
		),
	]
