# Generated by Django 2.2.6 on 2020-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0002_auto_20200418_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_address',
            field=models.CharField(default='random_address', max_length=127, unique=True),
            preserve_default=False,
        ),
    ]
